name: release

on:
  workflow_dispatch:
    inputs:
        version:
            description: 'Version to build'
            required: true
            type: string
  workflow_call:
    inputs:
        version:
            description: 'Version to build'
            required: true
            type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pms repo
        uses: actions/checkout@v4
        with:
          repository: plexinc/pms-docker
      - name: Get Package URL
        id: geturl
        run: |
          echo url=https://plex.tv/$(curl -s "https://plex.tv/downloads/details/5?build=linux-aarch64&channel=8&distro=debian&version=${{ inputs.version }}" | sed -n 's/.*file="\([^"]*\)".*/\1/p') >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.arm64
          platforms: linux/arm64
          build-args: |
            URL=${{ steps.geturl.outputs.url }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/plex-server:latest,${{ secrets.DOCKERHUB_USERNAME }}/plex-server:${{ inputs.version }}
